# Manually run Cypress tests stored in the /integrations folder of this repo

name: Run Cypress tests manually

on:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    # stop the job if it runs over 4 minutes
    # Dios me libre de usar todos los minutos de Github de Wiris
    timeout-minutes: 4
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Write the cypress.env.json file
        run: |
          echo '${{ secrets.CYPRESS_ENV_FILE }}' > cypress.env.json

      - name: Run all tests
        uses: cypress-io/github-action@v4
